---
- name: 運行ACS
  hosts: "{{ ACS_hostname }}"
  become: true
  tasks:
    - name: 運行ACS的container
      community.docker.docker_container:
        name: ACS
        image: inform-manage-server:latest
        detach: yes
        auto_remove: no
        interactive: yes
        privileged: no
        tty: yes
        ports: "{{ port_list }}"
        volumes:
          - "{{ ansible_playbook_path }}":/ansible_playbook
          - "{{ du_info_path }}":/info
          - "{{ tmp_du_info_path }}":/tmp
          - "{{ cpe_ssh_keys_path }}":/cpe_ssh_keys
          - "{{ ansible_host_path }}":/etc/ansible